version: '3'
services:
  sys:
    build:
      context: ./service/sys/rpc
      dockerfile: Dockerfile
    volumes:
      - ./service/sys/rpc/etc:/app/etc
    ports:
      - 1001:1001
  ums:
    build:
      context: ./service/ums/rpc
      dockerfile: Dockerfile
    volumes:
      - ./service/ums/rpc/etc:/app/etc
    ports:
      - 1003:1003
  sms:
    build:
      context: ./service/sms/rpc
      dockerfile: Dockerfile
    volumes:
      - ./service/sms/rpc/etc:/app/etc
    ports:
      - 1004:1004
  pms:
    build:
      context: ./service/pms/rpc
      dockerfile: Dockerfile
    volumes:
      - ./service/pms/rpc/etc:/app/etc
    ports:
      - 1002:1002
  oms:
    build:
      context: ./service/oms/rpc
      dockerfile: Dockerfile
    volumes:
      - ./service/oms/rpc/etc:/app/etc
    ports:
      - 1005:1005

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api/etc:/app/etc
    ports:
      - 6666:6666
    depends_on:
      - sys
      - ums
      - sms
      - pms
      - oms
  front-api:
    build:
      context: ./front-api
      dockerfile: Dockerfile
    volumes:
      - ./front-api/etc:/app/etc
    ports:
      - 8089:8089
    depends_on:
      - sys
      - ums
      - sms
      - pms
      - oms
